name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
      
        with:
          node-version: '16'

      - name: Install
        run: |
          npm i 

      - name: Build
        run: |
          npm run build
          
      - name: Deploy
        uses: crazy-max/ghaction-github-pages
        with:
          target_branch: gh-pages 
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}